

services:
#backend
  backend:
    build: ./backend
    ports:
      - "5050:5050"
    environment:
      - NODE_ENV=development
      - DB_PATH=/backend/data/db.sqlite
    volumes:
      - ./backend:/backend
      - /backend/node_modules
      - sqlite_data:/data
    
#frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    expose: 
    - "80"
    environment:
      NODE_ENV: development
      REACT_APP_API_URL: http://backend:5050  # URL for API requests
    depends_on:
      - backend
# nginx    
  nginx:
    image: nginx:stable
    container_name: nginx-proxy
    ports:
      - "3009:80"
    volumes:
      - ./frontend/build/:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
    
      - backend
    
# sqlite db

volumes:
  sqlite_data:  