version: "3.8"

services:
#backend
  backend:
    build: ./backend
    ports:
      - "5050:5050"
    environment:
      - NODE_ENV=production
      - DB_PATH=/backend/data/db.sqlite
    volumes:
      - ./backend:/backend
      - /backend/node_modules
      - sqlite_data:/data
    
#frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    expose:
      - "80"
    depends_on:
      - backend
  # nginx    
  nginx:
    image: nginx:stable
    container_name: nginx-proxy
    ports:
      - "3009:80"
    volumes:
      - ./frontend/build/:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
    
      - backend
    environment:
      NODE_ENV: production
      REACT_APP_API_URL: "/api"
   



# sqlite db

volumes:
  sqlite_data:  

  